apiVersion: apps/v1
kind: Deployment
metadata:
  name: azfuncapp
  namespace: prod
spec:
  selector:
      matchLabels:
        app: azfuncapp
  replicas: 1
  template:
      metadata:
        labels:
          app: azfuncapp
      spec:
        containers:
        - name: azfunc-repository-stats
          image: yvand/azfunc-repository-stats:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
          - name: FUNCTIONS_WORKER_RUNTIME
            value: 'node'
          - name: AzureWebJobsStorage
            valueFrom:
              secretKeyRef:
                name: azfuncapp
                key: AzureWebJobsStorage
          - name: COSMOS_CONNECTION
            valueFrom:
              secretKeyRef:
                name: azfuncapp
                key: COSMOS_CONNECTION
          - name: COSMOS_DATABASEID
            valueFrom:
              secretKeyRef:
                name: azfuncapp
                key: COSMOS_DATABASEID
          - name: COSMOS_COLLECTIONID
            valueFrom:
              secretKeyRef:
                name: azfuncapp
                key: COSMOS_COLLECTIONID
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: azfuncapp
                key: GITHUB_TOKEN
          - name: REPOSITORIES
            valueFrom:
              secretKeyRef:
                name: azfuncapp
                key: REPOSITORIES
