name: CI & Deploy to Azure Function App
on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened]
  # To trigger the workflow job 'deploy':
  # curl -H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: token <token>" \
  # --request POST --data '{"event_type": "trigger-deploy-to-azure", "client_payload": { "text": "a title"}}' https://api.github.com/repos/Yvand/azfunc-repository-stats/dispatches
  repository_dispatch:
    types:
      - trigger-deploy-to-azure

env:
  ARTIFACT_ZIP_NAME: azfunc-repository-stats.zip                     # Zip artifact name
  NODE_VERSION: '14.x'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build application
      run: |
        npm i -g azure-functions-core-tools
        npm ci
        npm run build:production
        echo $HOME
        
    - name: action-zip
      uses: montudor/action-zip@v1.0.0
      with:
        args: zip -qq -r ${{ env.ARTIFACT_ZIP_NAME }} .

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: azfunc-repository-stats-app
        path: ${{ github.workspace }}/${{ env.ARTIFACT_ZIP_NAME }}

  deploy:
    needs: build
    if: github.event.action == 'trigger-deploy-to-azure'
    runs-on: ubuntu-latest
    steps:
    - name: Echo github.event.action
      run: 'echo "github.event.action: ${{ github.event.action }}, github.event.client_payload.text: ${{ github.event.client_payload.text }}"'

    - name: 'Download artifact'
      uses: actions/download-artifact@v2
      with:
        name: azfunc-repository-stats-app
        path: ${{ github.workspace }}

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az functionapp deployment source config-zip -g ${{ secrets.AZURE_RESOURCE_GROUP }} -n ${{ secrets.AZURE_FUNCTIONAPP_NAME }} --src $GITHUB_WORKSPACE/${{ env.ARTIFACT_ZIP_NAME }}
