name: CI & Deploy to Azure Function App
on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened]
  # To trigger the workflow job 'deploy':
  # curl -H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: token <token>" \
  # --request POST --data '{"event_type": "trigger-deploy-to-azure", "client_payload": { "text": "a title"}}' https://api.github.com/repos/Yvand/azfunc-repository-stats/dispatches
  repository_dispatch:
    types:
      - trigger-deploy-to-azure
  workflow_dispatch:
    inputs:
      deploy_functions:
        type: choice
        description: 'Set to true to deploy the functions to Azure'
        options: 
          - true
          - false
        required: true
        default: 'false'

env:
  ARTIFACT_NAME: repository-statistics-artifact        # Artifact name
  ARTIFACT_APP_NAME: repository-statistics-app.zip     # Function app compiled and zipped (inside the artifact)

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build application
      run: |
        npm i -g azure-functions-core-tools
        npm ci
        npm run build
        npm prune --production
        
    - name: action-zip
      uses: montudor/action-zip@v1.0.0
      with:
        args: zip -qq -r ${{ env.ARTIFACT_APP_NAME }} .

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ github.workspace }}/${{ env.ARTIFACT_APP_NAME }}

  deploy:
    needs: build
    if: inputs.deploy_functions == 'true' || github.event.action == 'trigger-deploy-to-azure'
    runs-on: ubuntu-latest
    steps:
    - name: Echo github.event.action
      run: 'echo "github.event.action: ${{ github.event.action }}, github.event.client_payload.text: ${{ github.event.client_payload.text }}"'

    - name: 'Download artifact'
      uses: actions/download-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ github.workspace }}

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 'latest'
        inlineScript: |
          az functionapp deployment source config-zip -g ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_FUNCTIONAPP_NAME }} --src $GITHUB_WORKSPACE/${{ env.ARTIFACT_APP_NAME }}
