# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: |
        npm ci
        npm run build --if-present
        npm test
        echo $GITHUB_WORKSPACE
        echo $HOME
        cp $GITHUB_WORKSPACE $HOME/azfunc-repository-stats-app
        cd $HOME/azfunc-repository-stats-app
        rm -rf node_modules/
        echo $HOME
        ls $HOME/azfunc-repository-stats-app
      env:
        CI: true

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: azfunc-repository-stats-app
        path: $HOME/azfunc-repository-stats-app
